### ISSUE TITLE
Error Connection Refused

### ISSUE THREAD

**Issue by galuhboy123** [shokri-matin/Fed-eGlass#1]
Hello My Name is Galuh Boy H.
Im From Indonesia
I read your paper and try to replicate your code, for purposing of my homework in collage, 
but i got stuck when i try to connect from instance party to instance server. 
it says connection refused. (screenshoots attach)

I alredy do every steps, from video and paper, include install all requirement software form requirement.txt
what should i do for this error?

regards,
Galuh Boy H.
University of Indonesia
Depok, West Java.

**Comment by galuhboy123** [comment]
[
![Uploading connection refused.png…]()
](url)

**Comment by galuhboy123** [comment]
![connection refused](https://github.com/user-attachments/assets/00fdd689-a8c3-478d-a60b-d3c75972d417)

**Comment by shokri-matin** [comment]
Dear Galuh,

I have checked the code, and it worked properly. However, I have a few suggestions that may help:

1. Regarding the error "No such file or directory," I recommend cloning the entire project from GitHub using the command `git clone https://github.com/shokri-matin/Fed-eGlass.git` instead of manually copying files and folders. This error suggests that some files were not transferred correctly.

2. Create a virtual environment and ensure all the requirements and dependencies are installed by using the command `pip install -r requirements.txt`.

3. Ensure that the server is running before starting the clients, or double-check that the server is stable. The clients need to connect to the server for everything to work smoothly.

**Comment by galuhboy123** [comment]
Hai,
i alredy try your @shokri-matin suggestions, i make new instance in AWS Lightsail, then i copy entire project using git, and i do pip install the requirement.txt. but in process i have trouble install the Tensorflow, then i try intall Tensorflow with separate command line ("pip install tensorflow==2.9.1 --no-cache-dir") 

i make some assumption maybe Tensorflow is somehow broken or something? because if i use command ("pip install tensorflow==2.9.1") the instalation just says "killed" in the end of line status, and can't continue

and in the end, i still got connection refuse. I alredy check "manage" server using static IP, and add rule UDP and TCP and set 12345
maybe something i miss in process ? i still cant figure it out.

regards,
galuh boy h

![SS1 Server OK](https://github.com/user-attachments/assets/0c318d80-554f-470d-8969-f74307f62f26)
![SS2 party1 Failed](https://github.com/user-attachments/assets/dc78bf54-5c5b-47d9-af2e-f80e634195aa)

**Comment by galuhboy123** [comment]
hai . 
i alredy done the code, thanks for help
